---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        require_serial: true
        language: system
        types: [ python ]
      - id: ruff
        name: ruff
        # Remove --fix, in case you want it to disable autofix when this hook runs
        entry: uv run ruff check --fix --force-exclude
        require_serial: true
        language: system
        types: [ python ]
      - id: mypy
        name: mypy
        entry: uv run mypy .
        require_serial: true
        language: system
        types: [ python ]
        pass_filenames: false
      - id: migrations-check
        language: system
        name: Check for uncreated migrations
        entry: uv run python manage.py makemigrations --check --dry-run
        files: "(models\\.py$|(migrations/.+\\.py))"
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.22.2
    hooks:
    -   id: django-upgrade
        language_version: python3.12
        args: ["--target-version", "5.1"]
