# Generated by Django 5.1.6 on 2025-02-28 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name": "Flashcard",
                "verbose_name_plural": "Flashcards",
            },
        ),
        migrations.CreateModel(
            name="FlashCardSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Flashcard Set",
                "verbose_name_plural": "Flashcard Sets",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="FlashCardResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flashcards.flashcard", related_name="results"
                    ),
                ),
            ],
            options={
                "verbose_name": "Flashcard Result",
                "verbose_name_plural": "Flashcard Results",
            },
        ),
        migrations.AddField(
            model_name="flashcard",
            name="flashcard_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="flashcards", to="flashcards.flashcardset"
            ),
        ),
    ]
