# Generated by Django 5.1.6 on 2025-03-26 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcardset",
            name="description",
        ),
        migrations.RemoveField(
            model_name="flashcardset",
            name="is_active",
        ),
    ]
